const MESSAGES = [

  {"t": "msg", "f": "lena", "at": "19:22", "txt": "Kızlar", "gap": true},
  {"t": "msg", "f": "lena", "at": "19:22", "txt": "Acil yardım"},
  {"t": "msg", "f": "lena", "at": "19:22", "txt": "40 dk sonra çıkıyorum"},
  {"t": "msg", "f": "lena", "at": "19:22", "txt": "Hâlâ ne giyeceğimi bilmiyorum"},
  {"t": "msg", "f": "zoe", "at": "19:23", "txt": "LENAAA", "gap": true},
  {"t": "msg", "f": "zoe", "at": "19:23", "txt": "Sakin ol kızım vakit var"},
  {"t": "msg", "f": "lena", "at": "19:23", "txt": "Yok vakit yok", "gap": true},
  {"t": "msg", "f": "lena", "at": "19:23", "txt": "İki elbise arasında kaldım"},
  {"t": "photo", "f": "lena", "at": "19:24", "url": "s1e2_a_lena_navy.jpg", "cap": "Lacivert olanı"},
  {"t": "photo", "f": "lena", "at": "19:24", "url": "s1e2_a_lena_burgundy.jpg", "cap": "Bordo olanı"},
  {"t": "msg", "f": "lena", "at": "19:25", "txt": "Hangisi??", "gap": true},
  {"t": "msg", "f": "zoe", "at": "19:25", "txt": "İkisi de güzel ya", "gap": true},
  {"t": "msg", "f": "lena", "at": "19:25", "txt": "Bana yardım et", "gap": true},
  {"t": "msg", "f": "zoe", "at": "19:25", "txt": "Hımm", "gap": true},
  {"t": "choice", "at": "19:25", "options": [
    {"label": "A", "txt": "Lacivert elbise", "set": {"dress": "navy"}, "replies": [
      {"f": "lena", "at": "19:25", "txt": "Lacivert"},
      {"f": "lena", "at": "19:25", "txt": "Evet"},
      {"f": "lena", "at": "19:26", "txt": "Zoe sen ne düşünüyorsun?"},
      {"f": "zoe", "at": "19:26", "txt": "Lacivert daha asil durdu"}
    ]},
    {"label": "B", "txt": "Bordo elbise", "set": {"dress": "burgundy"}, "replies": [
      {"f": "lena", "at": "19:25", "txt": "Bordo"},
      {"f": "lena", "at": "19:25", "txt": "Biraz cesur ama bu akşam görünmek istiyorum aslında"},
      {"f": "lena", "at": "19:26", "txt": "Bilemedim, Zoe sen ne diyorsun?"},
      {"f": "zoe", "at": "19:26", "txt": "Bordo yanıyor"}
    ]}
  ]},
  {"t": "msg", "f": "lena", "at": "19:27", "txt": "Tamam elbise tamam", "gap": true},
  {"t": "msg", "f": "lena", "at": "19:27", "txt": "Şimdi ayakkabı"},
  {"t": "photo", "f": "lena", "at": "19:28", "url": "s1e2_a_lena_shoes.jpg", "cap": "Babet mi, topuklu mu??"},
  {"t": "choice", "at": "19:28", "options": [
    {"label": "A", "txt": "Babet", "set": {"shoe": "flat"}, "replies": [
      {"f": "lena", "at": "19:28", "txt": "Evet"},
      {"f": "lena", "at": "19:29", "txt": "Bütün akşam yürüyeceğim"},
      {"f": "zoe", "at": "19:29", "txt": "Evet evet, hemen ilk günden abartmayalım 🙂"}
    ]},
    {"label": "B", "txt": "Topuklu", "set": {"shoe": "heel"}, "replies": [
      {"f": "lena", "at": "19:28", "txt": "Alex 185cm"},
      {"f": "lena", "at": "19:29", "txt": "Topuklu ile ben de ona yaklaşayım"},
      {"f": "zoe", "at": "19:29", "txt": "Hadi bakalım, foto at"}
    ]}
  ]},
  {"t": "msg", "f": "lena", "at": "19:30", "txt": "Tamam son bir şey", "gap": true},
  {"t": "photo", "f": "lena", "at": "19:30", "url": "s1e2_a_lena_earrings.jpg", "cap": "Minimal inci mi, büyükannemin küpesi mi??"},
  {"t": "choice", "at": "19:31", "options": [
    {"label": "A", "txt": "Minimal, ince küpe", "set": {"earring": "pearl"}, "replies": [
      {"f": "lena", "at": "19:31", "txt": "Hafif olsun"},
      {"f": "lena", "at": "19:31", "txt": "Abartıya gerek yok"},
      {"f": "zoe", "at": "19:32", "txt": "İyi seçim"}
    ]},
    {"label": "B", "txt": "Büyük küpe, büyükannenden", "set": {"earring": "grandma"}, "replies": [
      {"f": "lena", "at": "19:31", "txt": "O küpeler büyükannemden kalmıştı"},
      {"f": "lena", "at": "19:32", "txt": "Şans getirirler bana"},
      {"f": "zoe", "at": "19:32", "txt": "🥹"}
    ]}
  ]},
  {"t": "msg", "f": "lena", "at": "19:33", "txt": "Tamam", "gap": true},
  {"t": "photo", "f": "lena", "at": "19:33", "url": "s1e2_a_lena_ready_{dress}_{shoe}_{earring}.jpg", "cap": "Bu nasıl??"},
  {"t": "msg", "f": "zoe", "at": "19:34", "txt": "LENAAA", "gap": true},
  {"t": "msg", "f": "zoe", "at": "19:34", "txt": "Çok güzelsin"},
  {"t": "msg", "f": "lena", "at": "19:34", "txt": "Sağ ol", "gap": true},
  {"t": "msg", "f": "lena", "at": "19:35", "txt": "Ben çıkıyorum"},
  {"t": "msg", "f": "lena", "at": "19:35", "txt": "Şans dileyin"},
  {"t": "msg", "f": "zoe", "at": "19:35", "txt": "Bol şans canım, çok eğlen", "gap": true},
  {"t": "msg", "f": "zoe", "at": "19:50", "txt": "Ben de size bir şey anlatıcam ama"},
  {"t": "msg", "f": "zoe", "at": "19:50", "txt": "Lena taksideymiş sonra okur"},
  {"t": "msg", "f": "zoe", "at": "19:51", "txt": "Sana anlatıyım o zaman"},
  {"t": "silence", "x": "8 saniye"},
  {"t": "msg", "f": "zoe", "at": "19:51", "txt": "Marc bu sabah kahvaltı hazırladı", "gap": true},
  {"t": "msg", "f": "zoe", "at": "19:52", "txt": "Erken uyandım ben"},
  {"t": "msg", "f": "zoe", "at": "19:52", "txt": "Normalde ben yaparım kahvaltıyı"},
  {"t": "msg", "f": "zoe", "at": "19:52", "txt": "Mutfağa girdiğimde masa hazırdı"},
  {"t": "msg", "f": "zoe", "at": "19:52", "txt": "Çay demlenmiş"},
  {"t": "msg", "f": "zoe", "at": "19:52", "txt": "Tabakta meyve kesmiş"},
  {"t": "msg", "f": "zoe", "at": "19:53", "txt": "Masaya çiçek koymuş bir de"},
  {"t": "msg", "f": "zoe", "at": "19:53", "txt": "Vazodakinden değil ha"},
  {"t": "msg", "f": "zoe", "at": "19:53", "txt": "Balkondan küçük bir tane koparmış"},
  {"t": "msg", "f": "zoe", "at": "19:54", "txt": "\"günün güzel geçsin\" dedi"},
  {"t": "msg", "f": "zoe", "at": "19:55", "txt": "Bu adam bazen çok tatlı ya"},
  {"t": "choice", "at": "19:56", "options": [{"label": "A", "txt": "Bunu hak ediyorsun Zoe", "replies": [{"f": "zoe", "at": "19:56", "txt": "Teşekkürler"}, {"f": "zoe", "at": "19:56", "txt": "Bugün içim rahat"}, {"f": "zoe", "at": "19:57", "txt": "Son günlerimdeki o his gitmiş gibi"}]}, {"label": "B", "txt": "Güzel, şu ara çok mu tatlı?", "replies": [{"f": "zoe", "at": "19:56", "txt": "Ya"}, {"f": "zoe", "at": "19:57", "txt": "Niye bu kadar şüpheleniyorum kendimden"}, {"f": "zoe", "at": "19:57", "txt": "Öyle düşünmek bile istemiyorum"}]}]},
  {"t": "msg", "f": "zoe", "at": "19:58", "txt": "Neyse", "gap": true},
  {"t": "msg", "f": "zoe", "at": "19:58", "txt": "Lena'dan haber yok"},
  {"t": "msg", "f": "zoe", "at": "19:58", "txt": "Sabredelim"},
  {"t": "silence", "x": "20 dakika"},
  {"t": "msg", "f": "lena", "at": "20:18", "txt": "Geldim", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:18", "txt": "O henüz gelmedi"},
  {"t": "msg", "f": "lena", "at": "20:19", "txt": "Ben biraz erken gelmişim ne aptalım"},
  {"t": "msg", "f": "lena", "at": "20:20", "txt": "Çok hevesli göründüm"},
  {"t": "msg", "f": "zoe", "at": "20:20", "txt": "Sakin ol kızım, 🙂", "gap": true},
  {"t": "msg", "f": "zoe", "at": "20:20", "txt": "Telefonla oyalan"},
  {"t": "msg", "f": "lena", "at": "20:21", "txt": "Oyalıyorum zaten sizin mesajlara bakıyorum", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:21", "txt": "Dur"},
  {"t": "silence", "x": "4 dakika"},
  {"t": "msg", "f": "lena", "at": "20:25", "txt": "Geldi", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:25", "txt": "Hadi kızlar"},
  {"t": "msg", "f": "lena", "at": "20:26", "txt": "Sonra yazarım"},
  {"t": "silence", "x": "25 dakika"},
  {"t": "msg", "f": "zoe", "at": "20:51", "txt": "Lena hala oradadır", "gap": true},
  {"t": "msg", "f": "zoe", "at": "20:51", "txt": "Ben kendi akşamımı anlatıyım sana"},
  {"t": "msg", "f": "zoe", "at": "20:52", "txt": "Marc'la yemek yedik evde"},
  {"t": "msg", "f": "zoe", "at": "20:53", "txt": "Şimdi kanepedeyiz"},
  {"t": "msg", "f": "zoe", "at": "20:53", "txt": "Marc tv'yi açtı"},
  {"t": "msg", "f": "zoe", "at": "20:53", "txt": "\"bu akşam senin sevdiğin şey izleyelim\" dedi"},
  {"t": "msg", "f": "zoe", "at": "20:54", "txt": "Hani yıllardır izlediğim sex and the city var ya"},
  {"t": "msg", "f": "zoe", "at": "20:54", "txt": "Marc dalga geçer normalde"},
  {"t": "msg", "f": "zoe", "at": "20:55", "txt": "Bu sefer kendisi açtı"},
  {"t": "photo", "f": "zoe", "at": "20:56", "url": "s1e2_d_zoe_couch.jpg", "cap": "Böyle bir akşam 🥹"},
  {"t": "msg", "f": "zoe", "at": "20:56", "txt": "Battaniyeyi de üzerime örttü"},
  {"t": "choice", "at": "20:57", "options": [{"label": "A", "txt": "İyi bir akşam geçir, tadını çıkar", "replies": [{"f": "zoe", "at": "20:57", "txt": "Çıkarıyorum"}, {"f": "zoe", "at": "20:58", "txt": "Uzun zamandır böyle hissetmemiştim"}, {"f": "zoe", "at": "20:58", "txt": "Basit bir akşam ama iyi geldi"}]}, {"label": "B", "txt": "Fazla efor sarf ediyor sanki", "replies": [{"f": "zoe", "at": "20:57", "txt": "Ne yani efor sarf etmesin mi"}, {"f": "zoe", "at": "20:58", "txt": "Adam bana sex and the city açtı"}, {"f": "zoe", "at": "20:58", "txt": "Şüpheci olmak istemiyorum"}]}]},
  {"t": "msg", "f": "zoe", "at": "21:00", "txt": "Lena'dan haber aldın mı", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:00", "txt": "Ben gruba bakmıyorum ama merak ettim"},
  {"t": "silence", "x": "18 dakika"},
  {"t": "msg", "f": "lena", "at": "21:18", "txt": "Tuvaletteyim 2 dk", "gap": true},
  {"t": "msg", "f": "lena", "at": "21:18", "txt": "Çok iyi gidiyor"},
  {"t": "msg", "f": "zoe", "at": "21:19", "txt": "DETAY LENA", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:19", "txt": "DETAY"},
  {"t": "msg", "f": "lena", "at": "21:20", "txt": "Komik", "gap": true},
  {"t": "msg", "f": "lena", "at": "21:20", "txt": "Dinliyor"},
  {"t": "msg", "f": "lena", "at": "21:20", "txt": "Gözlerimin içine bakıyor"},
  {"t": "msg", "f": "lena", "at": "21:21", "txt": "Ben çok konuşuyorum sanırım ama sorular soruyor"},
  {"t": "silence", "x": "35 saniye"},
  {"t": "msg", "f": "lena", "at": "21:21", "txt": "Dönüyorum", "gap": true},
  {"t": "msg", "f": "lena", "at": "21:22", "txt": "Sonra yazarım"},
  {"t": "silence", "x": "18 dakika"},
  {"t": "msg", "f": "lena", "at": "21:40", "txt": "Bir şey daha", "gap": true},
  {"t": "msg", "f": "lena", "at": "21:41", "txt": "Konuşurken bir arkadaşından bahsetti"},
  {"t": "msg", "f": "lena", "at": "21:41", "txt": "Bir kız"},
  {"t": "msg", "f": "lena", "at": "21:42", "txt": "Çok yakın arkadaşlarmış"},
  {"t": "msg", "f": "lena", "at": "21:42", "txt": "Finans sektöründeymiş"},
  {"t": "choice", "at": "21:43", "options": [{"label": "A", "txt": "İsim verdi mi, sor tekrar", "replies": [{"f": "lena", "at": "21:43", "txt": "Soracağım"}, {"f": "lena", "at": "21:44", "txt": "İsmini söylemedi sanırım"}, {"f": "lena", "at": "21:44", "txt": "Ama uzun süredir tanıştıklarını söyledi"}, {"f": "zoe", "at": "21:45", "txt": "Finans mı"}, {"f": "zoe", "at": "21:45", "txt": "Marc da finansta"}, {"f": "lena", "at": "21:45", "txt": "Finans dünyası küçüktür, herkes herkesi tanır"}]}, {"label": "B", "txt": "Tadını çıkar, detay sonra", "replies": [{"f": "lena", "at": "21:43", "txt": "Tamam"}, {"f": "lena", "at": "21:44", "txt": "O da masaya geldi zaten"}, {"f": "lena", "at": "21:44", "txt": "Yazarım sonra"}, {"f": "lena", "at": "21:45", "txt": "Ha bir de bir arkadaşından bahsetmişti aklımda tutayım"}]}]},
  {"t": "msg", "f": "lena", "at": "21:46", "txt": "Geldi", "gap": true},
  {"t": "msg", "f": "lena", "at": "21:46", "txt": "Sonra yazarım"},
  {"t": "silence", "x": "saatler geçiyor"},
  {"t": "msg", "f": "lena", "at": "23:02", "txt": "Döndüm", "gap": true},
  {"t": "msg", "f": "lena", "at": "23:02", "txt": "Kızlar"},
  {"t": "msg", "f": "lena", "at": "23:03", "txt": "Çok iyiydi"},
  {"t": "msg", "f": "zoe", "at": "23:03", "txt": "ANLAT HEMEN", "gap": true},
  {"t": "msg", "f": "zoe", "at": "23:03", "txt": "Merak içindeyim"},
  {"t": "msg", "f": "lena", "at": "23:04", "txt": "Nereden başlasam", "gap": true},
  {"t": "msg", "f": "lena", "at": "23:04", "txt": "Komik ya"},
  {"t": "msg", "f": "lena", "at": "23:05", "txt": "Espri anlayışım onunkiyle uyuyor"},
  {"t": "msg", "f": "lena", "at": "23:05", "txt": "Çok güldüm"},
  {"t": "msg", "f": "lena", "at": "23:06", "txt": "Ve dinliyor Zoe"},
  {"t": "msg", "f": "lena", "at": "23:06", "txt": "Ben anlatıyorum, sorular soruyor"},
  {"t": "msg", "f": "lena", "at": "23:06", "txt": "Sonra kendinden anlatıyor"},
  {"t": "msg", "f": "lena", "at": "23:07", "txt": "Yürürken bile rahattım"},
  {"t": "msg", "f": "lena", "at": "23:07", "txt": "Biliyorsun ilk buluşmalarda biraz kasarım ben"},
  {"t": "msg", "f": "lena", "at": "23:08", "txt": "Heyecanlandım"},
  {"t": "msg", "f": "lena", "at": "23:08", "txt": "Ama kendimi kaptırmamaya çalışıyorum"},
  {"t": "choice", "at": "23:09", "options": [{"label": "A", "txt": "Bırak kendini Lena, güzel bir şey yaşıyorsun", "replies": [{"f": "lena", "at": "23:09", "txt": "Biliyorum"}, {"f": "lena", "at": "23:10", "txt": "Ama hep eski yerlerime çekiliyorum"}, {"f": "lena", "at": "23:10", "txt": "Bir parçam \"fazla heyecanlanma\" diyor"}, {"f": "lena", "at": "23:11", "txt": "Bakalım"}]}, {"label": "B", "txt": "Temkinli olman da güzel", "replies": [{"f": "lena", "at": "23:09", "txt": "Beni tanıyorsunuz"}, {"f": "lena", "at": "23:10", "txt": "Fazla umutlanmak istemiyorum"}, {"f": "lena", "at": "23:10", "txt": "Önce biraz alışmam lazım"}, {"f": "zoe", "at": "23:11", "txt": "Akıllıca"}]}]},
  {"t": "msg", "f": "lena", "at": "23:12", "txt": "Bir şey daha var", "gap": true},
  {"t": "msg", "f": "lena", "at": "23:12", "txt": "Söylemem gerek"},
  {"t": "msg", "f": "lena", "at": "23:13", "txt": "Alex'in bir hikayesi var"},
  {"t": "msg", "f": "lena", "at": "23:13", "txt": "Eski bir ilişki"},
  {"t": "msg", "f": "lena", "at": "23:13", "txt": "Tam anlatmadı"},
  {"t": "msg", "f": "lena", "at": "23:14", "txt": "Ama sohbet o tarafa gitti bir an"},
  {"t": "msg", "f": "lena", "at": "23:14", "txt": "Sonra geri çekti"},
  {"t": "msg", "f": "lena", "at": "23:14", "txt": "\"uzun bir konu, sonra\" dedi"},
  {"t": "msg", "f": "zoe", "at": "23:15", "txt": "Zamanla anlatır", "gap": true},
  {"t": "msg", "f": "lena", "at": "23:15", "txt": "Umarım", "gap": true},
  {"t": "msg", "f": "lena", "at": "23:15", "txt": "Ben de kendiminkileri anlatacağım nasıl olsa"},
  {"t": "msg", "f": "zoe", "at": "23:30", "txt": "Güzel bir akşamdı kızlar", "gap": true},
  {"t": "msg", "f": "zoe", "at": "23:30", "txt": "Hepimiz için"},
  {"t": "msg", "f": "lena", "at": "23:31", "txt": "Siz de iyi ki varsınız", "gap": true},
  {"t": "msg", "f": "zoe", "at": "23:32", "txt": "Sen de canım 🧡", "gap": true},
  {"t": "msg", "f": "lena", "at": "23:32", "txt": "İyi geceler", "gap": true},
  {"t": "msg", "f": "zoe", "at": "23:33", "txt": "İyi geceler Lena", "gap": true},
  {"t": "msg", "f": "zoe", "at": "23:33", "txt": "Sana da iyi geceler"},
  {"t": "silence", "x": "2 dakika"},
  {"t": "msg", "f": "zoe", "at": "23:35", "txt": "Marc hâlâ kalkmadı bilgisayardan", "gap": true},
  {"t": "msg", "f": "zoe", "at": "23:35", "txt": "Tatlıcık"},
  {"t": "msg", "f": "zoe", "at": "23:36", "txt": "Bi şeye güldü şimdi kendi kendine"},
  {"t": "msg", "f": "zoe", "at": "23:36", "txt": "Mutluluğa bak"},
  {"t": "msg", "f": "zoe", "at": "23:36", "txt": "Neyse ben yatıyorum"},
  {"t": "silence", "x": "ekran kararır"},

];
