const MESSAGES = [

  {"t": "msg", "f": "lena", "at": "21:10", "txt": "Kızlar öldüm", "gap": true},
  {"t": "msg", "f": "lena", "at": "21:10", "txt": "Bugün bacak günü"},
  {"t": "msg", "f": "lena", "at": "21:11", "txt": "Yarın yürüyemeyeceğim kesin"},
  {"t": "photo", "f": "lena", "at": "21:11", "url": "lena_gym.jpg", "cap": "Gururlu hehee"},
  {"t": "msg", "f": "zoe", "at": "21:12", "txt": "LENAAAA", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:12", "txt": "Sen nasıl bir insansın"},
  {"t": "msg", "f": "zoe", "at": "21:12", "txt": "Ben bugün asansörün dördüncü kata çıkmasını beklerken yoruldum"},
  {"t": "photo", "f": "zoe", "at": "21:13", "url": "zoe_cozy.jpg", "cap": "Benim gecem 🥹"},
  {"t": "msg", "f": "zoe", "at": "21:13", "txt": "Yorgan + çay"},
  {"t": "msg", "f": "zoe", "at": "21:14", "txt": "Ben de yarından itibaren spora başlıyorum"},
  {"t": "msg", "f": "lena", "at": "21:14", "txt": "Zoe 2022 den beri \"yarından itibaren\" diyorsun", "gap": true},
  {"t": "msg", "f": "lena", "at": "21:14", "txt": "Hadi ama"},
  {"t": "choice", "at": "21:14", "options": [{"label": "A", "txt": "Lena haklı aslında, Zoe bir başlangıç tarihi koysan mı", "replies": [{"f": "zoe", "at": "21:15", "txt": "HSDGSDG"}, {"f": "zoe", "at": "21:15", "txt": "Tamam kızlar yarın sabah"}, {"f": "zoe", "at": "21:15", "txt": "Ya da pazartesi"}, {"f": "lena", "at": "21:16", "txt": "İşte başladı yine"}]}, {"label": "B", "txt": "Bazen en iyisi yorgan ve çay", "replies": [{"f": "zoe", "at": "21:15", "txt": "Hahahaha"}, {"f": "zoe", "at": "21:15", "txt": "Lena duydun mu sen"}, {"f": "lena", "at": "21:16", "txt": "Duydum duydum"}, {"f": "lena", "at": "21:16", "txt": "Peki siz oturun ben tek başıma spor yaparım ben"}]}]},
  {"t": "msg", "f": "lena", "at": "21:16", "txt": "Neyse", "gap": true},
  {"t": "msg", "f": "lena", "at": "21:16", "txt": "Marc'la nasıldı akşam"},
  {"t": "msg", "f": "lena", "at": "21:17", "txt": "Yemeğe gittiniz değil mi"},
  {"t": "msg", "f": "zoe", "at": "21:17", "txt": "Gittik güzeldi", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:18", "txt": "Yani bilmiyorum tabi"},
  {"t": "msg", "f": "lena", "at": "21:18", "txt": "Ne demek bilmiyorum", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:19", "txt": "Bu ara biraz garip ya", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:19", "txt": "Kafası başka bir yerde gibi"},
  {"t": "msg", "f": "zoe", "at": "21:20", "txt": "Nasıl desem"},
  {"t": "msg", "f": "zoe", "at": "21:20", "txt": "Karşımda oturuyor ama orada değil"},
  {"t": "msg", "f": "lena", "at": "21:20", "txt": "Nasıl yani", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:21", "txt": "Telefona çok bakıyor mesela", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:21", "txt": "Masaya yüzüstü koyuyor sürekli"},
  {"t": "msg", "f": "zoe", "at": "21:22", "txt": "Yemekte bile böyleydi"},
  {"t": "msg", "f": "zoe", "at": "21:22", "txt": "Belki yorgundur bilmiyorum"},
  {"t": "msg", "f": "lena", "at": "21:22", "txt": "Kaç haftadır böyle", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:23", "txt": "2-3 hafta falan", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:23", "txt": "Geçer herhalde 🙂"},
  {"t": "silence", "x": "18 saniye"},
  {"t": "choice", "at": "21:24", "options": [{"label": "A", "txt": "Sor bence, içini rahatlat", "replies": [{"f": "zoe", "at": "21:24", "txt": "Sorucam sorucam"}, {"f": "zoe", "at": "21:24", "txt": "Ama ne sorucam"}, {"f": "zoe", "at": "21:25", "txt": "\"telefona çok bakıyorsun\" desem aptal gibi olmuyor muyum"}, {"f": "lena", "at": "21:25", "txt": "Hayır neden öyle olasın"}, {"f": "lena", "at": "21:25", "txt": "O senin erkek arkadaşın sonuçta, merak ediyorsan soracaksın"}]}, {"label": "B", "txt": "Endişelenecek bir şey yoktur bence", "replies": [{"f": "zoe", "at": "21:24", "txt": "Evet bence de"}, {"f": "zoe", "at": "21:25", "txt": "Çok çalışıyor bu ara, overtime yapıyor sürekli"}, {"f": "lena", "at": "21:25", "txt": "İnanıyor musun gerçekten"}, {"f": "zoe", "at": "21:26", "txt": "Ya..."}]}]},
  {"t": "msg", "f": "zoe", "at": "21:47", "txt": "Aaaa", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:47", "txt": "Dur"},
  {"t": "msg", "f": "zoe", "at": "21:48", "txt": "Marc yazdı şimdi"},
  {"t": "msg", "f": "lena", "at": "21:48", "txt": "Ne dedi", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:49", "txt": "Hâlâ ofisteymiş", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:49", "txt": "Merak etme dedi"},
  {"t": "photo", "f": "zoe", "at": "21:50", "url": "twocups.jpg", "cap": "Foto attııı 🥹"},
  {"t": "msg", "f": "zoe", "at": "21:51", "txt": "Adam ölmüş çalışmaktan ya"},
  {"t": "msg", "f": "zoe", "at": "21:51", "txt": "Suçlu hissettim şimdi"},
  {"t": "silence", "x": "11 saniye, lena cevap yazmıyor"},
  {"t": "choice", "at": "21:52", "options": [{"label": "A", "txt": "Zoe o fotoğrafta iki fincan var, ikincisindeki ruj izi mi?", "replies": [{"f": "zoe", "at": "21:52", "txt": "Ne"}, {"f": "zoe", "at": "21:52", "txt": "Hangi fincan"}, {"f": "zoe", "at": "21:52", "txt": "Dur"}, {"f": "zoe", "at": "21:53", "txt": "Dur dur dur"}, {"f": "lena", "at": "21:53", "txt": "Ben de onu diyecektim şimdi"}, {"f": "lena", "at": "21:53", "txt": "Sağdaki fincan Zoe"}]}, {"label": "B", "txt": "Bak yoğun bir şekilde çalışıyor", "replies": [{"f": "lena", "at": "21:52", "txt": "Zoe"}, {"f": "lena", "at": "21:52", "txt": "Bir saniye"}, {"f": "lena", "at": "21:53", "txt": "Masada iki fincan var"}, {"f": "lena", "at": "21:53", "txt": "Sağdakinde ruj izi var"}, {"f": "zoe", "at": "21:53", "txt": "Ne"}, {"f": "zoe", "at": "21:53", "txt": "NE"}]}]},
  {"t": "msg", "f": "zoe", "at": "21:57", "txt": "Yani", "gap": true},
  {"t": "msg", "f": "zoe", "at": "21:57", "txt": "İş arkadaşı içmiştir değil mi"},
  {"t": "msg", "f": "zoe", "at": "21:58", "txt": "Ofiste herkes kahve içer"},
  {"t": "msg", "f": "zoe", "at": "21:58", "txt": "Biri bardağını Marc'ın masasına bırakmıştır"},
  {"t": "msg", "f": "zoe", "at": "21:59", "txt": "Bu kadar basit olabilir"},
  {"t": "msg", "f": "lena", "at": "21:59", "txt": "Olabilir tabii", "gap": true},
  {"t": "silence", "x": "22 saniye"},
  {"t": "msg", "f": "lena", "at": "22:00", "txt": "Ama sorabilirsin bence", "gap": true},
  {"t": "msg", "f": "lena", "at": "22:01", "txt": "İçin rahat etsin diye"},
  {"t": "choice", "at": "22:02", "options": [{"label": "A", "txt": "Sormazsan kafanda büyür, bir kez sor ve bitir", "replies": [{"f": "zoe", "at": "22:02", "txt": "Biliyorum"}, {"f": "zoe", "at": "22:03", "txt": "Ama nasıl sorucam ki"}, {"f": "lena", "at": "22:03", "txt": "Düz sorma tabii"}, {"f": "lena", "at": "22:04", "txt": "\"bugün ofiste kimler vardı\" gibi başla, adam kendi anlatır"}, {"f": "zoe", "at": "22:04", "txt": "Tamam sorarım"}, {"f": "zoe", "at": "22:04", "txt": "Bugün değil ama"}]}, {"label": "B", "txt": "Boşver sorma", "replies": [{"f": "zoe", "at": "22:02", "txt": "Haklısın"}, {"f": "zoe", "at": "22:03", "txt": "Birinin fincanı orada kalmıştır"}, {"f": "zoe", "at": "22:03", "txt": "Ben paranoyak oluyorum"}, {"f": "lena", "at": "22:04", "txt": "Ama yine de sor bence"}, {"f": "lena", "at": "22:04", "txt": "Sormazsan kafanda büyütüyorsun"}, {"f": "zoe", "at": "22:05", "txt": "Tamam bugün değil belki yarın sorarım"}]}]},
  {"t": "silence", "x": "ertesi akşam"},
  {"t": "msg", "f": "zoe", "at": "20:14", "txt": "Kızlar", "gap": true},
  {"t": "msg", "f": "zoe", "at": "20:14", "txt": "Sordum Marc'a"},
  {"t": "msg", "f": "lena", "at": "20:15", "txt": "NE ZAMAN", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:15", "txt": "Nasıl geçti anlat"},
  {"t": "msg", "f": "zoe", "at": "20:15", "txt": "Dün gece eve dönünce", "gap": true},
  {"t": "msg", "f": "zoe", "at": "20:16", "txt": "Sordum yatmadan önce"},
  {"t": "msg", "f": "zoe", "at": "20:16", "txt": "\"bugün ofiste kimler vardı\" dedim"},
  {"t": "msg", "f": "zoe", "at": "20:16", "txt": "Mümkün olduğunca havadan bir şekilde"},
  {"t": "msg", "f": "zoe", "at": "20:17", "txt": "\"iş arkadaşlarım, neden ki??\" dedi"},
  {"t": "msg", "f": "zoe", "at": "20:17", "txt": "Ben de \"yok merak ettim\" dedim"},
  {"t": "msg", "f": "zoe", "at": "20:17", "txt": "O da \"toplantı vardı o gün, baya yoğun çalıştık\" dedi"},
  {"t": "msg", "f": "zoe", "at": "20:18", "txt": "Sonra ekledi"},
  {"t": "msg", "f": "zoe", "at": "20:18", "txt": "\"neden sordun ki\""},
  {"t": "msg", "f": "zoe", "at": "20:19", "txt": "Ben de \"bir sebebi yok öylesine\" dedim"},
  {"t": "msg", "f": "zoe", "at": "20:19", "txt": "Sonra uyduk."},
  {"t": "msg", "f": "zoe", "at": "20:20", "txt": "Yanii, bence normal bir açıklama"},
  {"t": "msg", "f": "zoe", "at": "20:20", "txt": "Toplantı vardı ve masalarda bardaklar birikmiş olabilir"},
  {"t": "msg", "f": "zoe", "at": "20:21", "txt": "Ben de kendimi yedim sabaha kadar 😭"},
  {"t": "silence", "x": "14 saniye"},
  {"t": "choice", "at": "20:22", "options": [{"label": "A", "txt": "Açıklama mantıklı geliyor", "replies": [{"f": "zoe", "at": "20:22", "txt": "Değil mi"}, {"f": "zoe", "at": "20:22", "txt": "Ben de öyle düşünmek istiyorum"}, {"f": "lena", "at": "20:23", "txt": "Ben bir şey demicem"}, {"f": "lena", "at": "20:23", "txt": "Ama"}, {"f": "lena", "at": "20:24", "txt": "Adam \"neden sordun ki\" demiş"}, {"f": "lena", "at": "20:24", "txt": "Neden sordun ki niye önemli"}, {"f": "zoe", "at": "20:25", "txt": "..."}]}, {"label": "B", "txt": "\"neden sordun ki??\" biraz tuhaf sadece", "replies": [{"f": "lena", "at": "20:22", "txt": "Ben de onu diyecektim"}, {"f": "lena", "at": "20:23", "txt": "Sorulmayacak bir şeyse niye savunmaya geçiyor"}, {"f": "zoe", "at": "20:23", "txt": "Ya"}, {"f": "zoe", "at": "20:24", "txt": "Ben de takıldım oraya ama uzatmak istemedim"}, {"f": "zoe", "at": "20:24", "txt": "Yoksa kavga olcak"}, {"f": "lena", "at": "20:25", "txt": "Hmm."}]}]},
  {"t": "silence", "x": "kimse konuyu devam ettirmiyor"},
  {"t": "msg", "f": "lena", "at": "20:31", "txt": "Kızlar konuyu değiştiriyorum bir saniye 😅", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:32", "txt": "Yoksa bu akşam da böyle gidicek"},
  {"t": "msg", "f": "zoe", "at": "20:32", "txt": "Değiştir değiştir", "gap": true},
  {"t": "msg", "f": "zoe", "at": "20:32", "txt": "Ne oldu"},
  {"t": "msg", "f": "lena", "at": "20:33", "txt": "Bir fotoğraf atıyorum", "gap": true},
  {"t": "photo", "f": "lena", "at": "20:34", "url": "alex.jpg", "cap": "Ne dersinizz??"},
  {"t": "msg", "f": "zoe", "at": "20:34", "txt": "LENA", "gap": true},
  {"t": "msg", "f": "zoe", "at": "20:34", "txt": "LENA KİM BU"},
  {"t": "msg", "f": "zoe", "at": "20:35", "txt": "LENA BİZDEN NE SAKLIYORSUN 😭😭"},
  {"t": "msg", "f": "lena", "at": "20:35", "txt": "Haha", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:36", "txt": "Bir süredir yazışıyoruz"},
  {"t": "msg", "f": "lena", "at": "20:36", "txt": "Daha bir şey değil, sen sakin ol"},
  {"t": "msg", "f": "zoe", "at": "20:37", "txt": "Ne kadardır", "gap": true},
  {"t": "msg", "f": "zoe", "at": "20:37", "txt": "NEDEN SÖYLEMEDİN"},
  {"t": "msg", "f": "zoe", "at": "20:37", "txt": "Ben de sürekli kendi meselelerimden bahsediyorum"},
  {"t": "msg", "f": "lena", "at": "20:38", "txt": "Zoe", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:38", "txt": "Ondan değil"},
  {"t": "msg", "f": "lena", "at": "20:39", "txt": "Daha çok yeni"},
  {"t": "choice", "at": "20:40", "options": [{"label": "A", "txt": "Woww kim bu?", "replies": [{"f": "lena", "at": "20:40", "txt": "Ya işte"}, {"f": "lena", "at": "20:41", "txt": "Alex"}, {"f": "zoe", "at": "20:41", "txt": "ALEXX Mİ"}, {"f": "zoe", "at": "20:41", "txt": "Çift x ile mi 😭"}, {"f": "lena", "at": "20:42", "txt": "Zoe tek x"}, {"f": "lena", "at": "20:42", "txt": "Ama iki x de olabilir hak veriyorum"}]}, {"label": "B", "txt": "Bence Marc konusunu kapatıp sana geçelim şimdi", "replies": [{"f": "zoe", "at": "20:40", "txt": "Evet evet kapat konuyu"}, {"f": "zoe", "at": "20:41", "txt": "Lena adı ne"}, {"f": "lena", "at": "20:41", "txt": "Alex"}, {"f": "zoe", "at": "20:42", "txt": "ALEX"}, {"f": "zoe", "at": "20:42", "txt": "İsimden başladı iyi gidiyor"}, {"f": "lena", "at": "20:42", "txt": "😅"}]}]},
  {"t": "msg", "f": "zoe", "at": "20:43", "txt": "Ne iş yapıyor anlat", "gap": true},
  {"t": "msg", "f": "zoe", "at": "20:43", "txt": "Nasıl tanıştınız???"},
  {"t": "msg", "f": "lena", "at": "20:43", "txt": "Reklam ajansında creative director", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:44", "txt": "Ortak bir arkadaş var, geçen ay bir etkinlikte tanıştık"},
  {"t": "msg", "f": "lena", "at": "20:44", "txt": "O günden beri yazışıyoruz"},
  {"t": "msg", "f": "zoe", "at": "20:45", "txt": "Buluştunuz mu", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:45", "txt": "Henüz hayır", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:46", "txt": "Bu haftasonu belki 🙂"},
  {"t": "choice", "at": "20:46", "options": [{"label": "A", "txt": "Hımm iyi görünüyor.", "replies": [{"f": "lena", "at": "20:47", "txt": "Değil mi??"}, {"f": "lena", "at": "20:47", "txt": "Bence de tatlı bakışları var"}, {"f": "zoe", "at": "20:48", "txt": "Anladım anladım haftasonuna kadar bunu konuşacaz"}, {"f": "lena", "at": "20:48", "txt": "😅"}]}, {"label": "B", "txt": "Beğenmedim", "replies": [{"f": "lena", "at": "20:47", "txt": "Ne"}, {"f": "lena", "at": "20:47", "txt": "Niye"}, {"f": "zoe", "at": "20:47", "txt": "Yaaa"}, {"f": "zoe", "at": "20:48", "txt": "Kıza laf demeyin daha sevmeden"}, {"f": "zoe", "at": "20:48", "txt": "Lena çok yakışıklı bence kafana takma"}, {"f": "lena", "at": "20:49", "txt": "Tamam ama ben de bir kere baktım yeniden"}, {"f": "lena", "at": "20:49", "txt": "Belki çok hayalimde büyütmüşümdür"}]}]},
  {"t": "msg", "f": "lena", "at": "20:49", "txt": "Yatıyorum ben", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:49", "txt": "Yarın sabah işler var erken kalkıcam"},
  {"t": "msg", "f": "zoe", "at": "20:50", "txt": "İyi geceler Lenaaa 🧡", "gap": true},
  {"t": "msg", "f": "zoe", "at": "20:50", "txt": "Alex hakkında çok daha fazla konuşucaz hazır ol"},
  {"t": "msg", "f": "lena", "at": "20:51", "txt": "Hazırım", "gap": true},
  {"t": "msg", "f": "lena", "at": "20:51", "txt": "İyi geceler 🙂"},
  {"t": "silence", "x": "saatler geçiyor"},
  {"t": "channel", "id": "zoe_dm", "divider": "zoe · özel sohbet"},
  {"t": "msg", "f": "zoe", "at": "23:47", "txt": "Uyanık mısın", "gap": true},
  {"t": "silence", "x": "22 saniye"},
  {"t": "msg", "f": "zoe", "at": "23:48", "txt": "Gruba yazamadım", "gap": true},
  {"t": "msg", "f": "zoe", "at": "23:48", "txt": "O uyudu zaten"},
  {"t": "msg", "f": "zoe", "at": "23:49", "txt": "Bir de ona sorarsam \"sor Marc'a\" diyecek"},
  {"t": "msg", "f": "zoe", "at": "23:50", "txt": "Ama içim rahat etmedi"},
  {"t": "choice", "at": "23:51", "options": [{"label": "A", "txt": "Zoe bence bu akşam burada bırak, yarın konuşursunuz tekrar", "replies": [{"f": "zoe", "at": "23:51", "txt": "Bırakmak istiyorum"}, {"f": "zoe", "at": "23:52", "txt": "Ama gözlerim açık tavana bakıyorum"}, {"f": "zoe", "at": "23:52", "txt": "Çok hazır cevaptı bugün"}, {"f": "zoe", "at": "23:53", "txt": "Sanki bekliyormuş gibi"}, {"f": "zoe", "at": "23:53", "txt": "Normalde \"ne fark eder ki\" tipi cevaplar verir"}, {"f": "zoe", "at": "23:53", "txt": "Bu sefer öyle olmadı"}]}, {"label": "B", "txt": "Anlatmadığın başka bir şey var galiba, söylesene", "replies": [{"f": "zoe", "at": "23:51", "txt": "..."}, {"f": "zoe", "at": "23:52", "txt": "Var"}, {"f": "zoe", "at": "23:52", "txt": "Biliyordum soracağını"}, {"f": "zoe", "at": "23:53", "txt": "Tam olarak bir şey değil ya"}, {"f": "zoe", "at": "23:53", "txt": "Ama kafamda takılıyor"}]}]},
  {"t": "msg", "f": "zoe", "at": "23:54", "txt": "Bu ara çok tatlı aslında", "gap": true},
  {"t": "msg", "f": "zoe", "at": "23:54", "txt": "Çok çok tatlı"},
  {"t": "msg", "f": "zoe", "at": "23:55", "txt": "İki hafta önce bir saat almış bana"},
  {"t": "msg", "f": "zoe", "at": "23:55", "txt": "Aylardır konuştuğum bir saat"},
  {"t": "msg", "f": "zoe", "at": "23:56", "txt": "Sormadan aldı getirdi"},
  {"t": "msg", "f": "zoe", "at": "23:56", "txt": "Eve gelirken"},
  {"t": "msg", "f": "zoe", "at": "23:56", "txt": "Çok sevindim, duygulandım hatta 🥹"},
  {"t": "choice", "at": "23:57", "options": [{"label": "A", "txt": "Seni nasıl mutlu edeceğini biliyor", "replies": [{"f": "zoe", "at": "23:57", "txt": "Tam olarak bunu hissetmiştim"}, {"f": "zoe", "at": "23:58", "txt": "İlk günlerimizdeki gibiydi"}, {"f": "zoe", "at": "23:58", "txt": "O yüzden iki fincanı görünce şaşırdım"}, {"f": "zoe", "at": "23:59", "txt": "Şu ara bana çok iyi davranan bir adam nasıl aynı zamanda"}, {"f": "zoe", "at": "23:59", "txt": "Neyse"}]}, {"label": "B", "txt": "Normalde olduğundan daha tatlı olması biraz tuhaf değil mi?", "replies": [{"f": "zoe", "at": "23:57", "txt": "..."}, {"f": "zoe", "at": "23:58", "txt": "Öyle düşünmek istemiyorum"}, {"f": "zoe", "at": "23:58", "txt": "Çünkü öyleyse cidden çok fena"}, {"f": "zoe", "at": "23:59", "txt": "Dayanamam buna"}, {"f": "zoe", "at": "23:59", "txt": "Ama aklımdan geçmedi değil"}]}]},
  {"t": "msg", "f": "zoe", "at": "00:01", "txt": "Bir de", "gap": true},
  {"t": "msg", "f": "zoe", "at": "00:01", "txt": "Saati aldığı gün"},
  {"t": "msg", "f": "zoe", "at": "00:02", "txt": "İki hafta önceki cumartesi"},
  {"t": "msg", "f": "zoe", "at": "00:02", "txt": "İş seyahatinden dönmüştü"},
  {"t": "msg", "f": "zoe", "at": "00:03", "txt": "3 günlük bir seyahat"},
  {"t": "msg", "f": "zoe", "at": "00:03", "txt": "Haftasonu için yönetim takımı toplantısı demişti"},
  {"t": "msg", "f": "zoe", "at": "00:04", "txt": "Saati de dönüşte havaalanından almış"},
  {"t": "silence", "x": "9 saniye"},
  {"t": "choice", "at": "00:05", "options": [{"label": "A", "txt": "Hafta sonu yurt dışı toplantısı olağan değil gibi geldi", "replies": [{"f": "zoe", "at": "00:05", "txt": "Onların şirketi garip çalışıyor biliyorsun"}, {"f": "zoe", "at": "00:06", "txt": "Yatırım işleri var bazen haftasonuna kayıyor"}, {"f": "zoe", "at": "00:06", "txt": "Ama sen soyunca ben de bir tuhaf oldum"}, {"f": "zoe", "at": "00:07", "txt": "Neden bu kadar şüpheleniyorum ki şu an ya"}]}, {"label": "B", "txt": "Seyahat dönüşü hediye zamanlaması ilginç, tesadüf olabilir tabii", "replies": [{"f": "zoe", "at": "00:05", "txt": "Ne demek istiyorsun"}, {"f": "zoe", "at": "00:06", "txt": "..."}, {"f": "zoe", "at": "00:06", "txt": "Tamam dedin ama demek istediğini anladım"}, {"f": "zoe", "at": "00:07", "txt": "Kapatıcam şimdi telefonu"}, {"f": "zoe", "at": "00:07", "txt": "Yoksa sabaha kadar düşünürüm"}]}]},
  {"t": "choice", "at": "00:08", "options": [{"label": "A", "txt": "Marc'la sabah konuş, gözlerine bakarak", "replies": [{"f": "zoe", "at": "00:08", "txt": "Belki"}, {"f": "zoe", "at": "00:09", "txt": "Ama nasıl konuşacağım bilmiyorum"}, {"f": "zoe", "at": "00:09", "txt": "\"iki fincanı sordum sen geçiştirdin\" mi diyeceğim"}, {"f": "zoe", "at": "00:10", "txt": "\"neden saat aldın\" mı"}, {"f": "zoe", "at": "00:10", "txt": "Aklım karışık çok"}, {"f": "zoe", "at": "00:11", "txt": "Yatıyorum, iyi geceler"}]}, {"label": "B", "txt": "Marc şu an yanında galiba, ona bakarak ne hissediyorsun", "replies": [{"f": "zoe", "at": "00:08", "txt": "Yanımda"}, {"f": "zoe", "at": "00:09", "txt": "Uyuyor"}, {"f": "zoe", "at": "00:09", "txt": "Sessizce yazıyorum ona dokunmadan"}, {"f": "zoe", "at": "00:10", "txt": "Şu an yüzüne bakıyorum"}, {"f": "zoe", "at": "00:10", "txt": "Tanıdığım yüz"}, {"f": "zoe", "at": "00:11", "txt": "Ama hiçbir şey anlamıyorum"}]}]},
  {"t": "silence", "x": "uzun sessizlik"},
  {"t": "msg", "f": "zoe", "at": "00:14", "txt": "Sen de uyu artık", "gap": true},
  {"t": "msg", "f": "zoe", "at": "00:14", "txt": "Yarın konuşuruz"},
  {"t": "msg", "f": "zoe", "at": "00:15", "txt": "İyi geceler 🙂"},
  {"t": "silence", "x": "ekran kararır. gece biter."},

];
